# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  # - name: Resume
  #   url: '/resume/'
  #   weight: 20  
  - name: Publications
    url: '/publications/'
    weight: 30
  - name: Talks
    url: '/talks/'
    weight: 40
  - name: Comedy
    url: '/comedy/'
    weight: 50
  - name: Blog
    url: https://yuanmohe.substack.com/
    weight: 60
  - name: Poem
    url: '/poem/'
    weight: 70  


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
